Adding particle package in utils
flarefly/flarefly pull request #29
Opened 2022-09-18 16:41 UTC by stefanopolitano

This PR contains:

- addition of "particle" package (https://github.com/scikit-hep/particle)
- modification of particle mass getter function

2022-09-19 15:28 UTC, fgrosa requested changes
Hi @stefanopolitano! I was wondering whether we need these functions at all, wouldn't it be sufficient to call `Particle.from_pdgid(pdg_id).mass` or `Particle.from_name(pdg_name).mass` in the `set_particle_mass` method here https://github.com/flarefly/flarefly/blob/7c571e1bc11ff5b2ebbc6aa8f3a64368472233b5/flarefly/fitter.py#L781? You can move the `mass` parameter in the `kwargs` and add the `pdg_code` and the `name` and then use the corresponding setter if one or the other is set

2022-09-19 15:39 UTC, stefanopolitano commented
Hi @fgrosa, I implemented this function as a substitute of the previous one but indeed, we can just use the particle package in the fitter. 
Regarding the requirements I forgot: I will add it. Thanks!

2022-09-19 15:42 UTC, fgrosa commented
> Hi @fgrosa, I implemented this function as a substitute of the previous one but indeed, we can just use the particle package in the fitter. Regarding the requirements I forgot: I will add it. Thanks!

Yes I would simply put it in the fitter, since the functions provided by the `particle` package already give us all that we need 👍

2022-09-20 06:55 UTC, stefanopolitano commented
Hi @fgrosa, I think I'm getting the same error you got with macos

2022-09-20 07:19 UTC, fgrosa requested changes
Thanks @stefanopolitano! I just suggested you a small modification to have all the possible arguments in the `kwargs`

2022-09-20 07:19 UTC, fgrosa commented on flarefly/fitter.py
> +    def set_particle_mass(self, idx, pdg_id=-999, pdg_name='', **kwargs):
```suggestion
    def set_particle_mass(self, idx, **kwargs):
```

2022-09-20 07:19 UTC, fgrosa commented on flarefly/fitter.py
> +            Name of the particle
```suggestion
```

2022-09-20 07:19 UTC, fgrosa commented on flarefly/fitter.py
> +            mass = Particle.from_name(pdg_name).mass*1e-3
```suggestion
        if 'mass' in kwargs:
            mass = kwargs['mass']
        elif 'pdg_id' in kwargs:
            mass = Particle.from_pdgid(kwargs['pdg_id']).mass*1e-3
        elif 'pdg_name' in kwargs:
            mass = Particle.from_name(kwargs['pdg_name']).mass*1e-3
        else:
            Logger(f'"mass", "pdg_id", and "pdg_name" not provided, mass value for signal {idx} will not be set',
                         'ERROR')
```

2022-09-20 07:19 UTC, fgrosa commented on flarefly/fitter.py
> +                name of the mass variable
```suggestion
            - mass: float
                The mass of the particle
            - pdg_id: int
                PDG ID of the particle (alternative to mass)
            - pdg_name: str
                Name of the particle (alternative to mass)
```

2022-09-20 07:19 UTC, fgrosa commented on tests/test_massfitter_binned.py
> +FITTERBINNED.set_particle_mass(1, mass=2.010, limits=[2.000, 2.020])
Let's test also a different argument
```suggestion
FITTERBINNED.set_particle_mass(1, pdg_id=413, limits=[2.000, 2.020])
```

2022-09-20 07:23 UTC, fgrosa commented
> Hi @fgrosa, I think I'm getting the same error you got with macos

Now it breaks on wheel installation, it might be that we have to modify a bit the `setup.py`, but let's do it in another PR (I opened an issue https://github.com/flarefly/flarefly/issues/30)

2022-09-20 07:25 UTC, fgrosa approved these changes

2022-09-20 14:05 UTC, fgrosa requested changes

2022-09-20 14:05 UTC, fgrosa commented on tests/test_massfitter_binned.py
>  FITTERBINNED.set_signal_initpar(1, 'sigma', 0.015)
To make the fit converge and pass the test
```suggestion
FITTERBINNED.set_signal_initpar(1, 'sigma', 0.015, limits=[0.01, 0.03])
```

2022-09-20 14:21 UTC, fgrosa approved these changes

2022-09-20 14:28 UTC, merged