Adding polynomial function as bkg pdf
flarefly/flarefly pull request #32
Opened 2022-09-28 11:55 UTC by stefanopolitano

This PR contains:
-   implementation of "pol _n_ "as bkg pdf in fitter.py (based on zfit.pdf.Chebyshev)

2022-09-28 12:03 UTC, fgrosa requested changes
Ciao @stefanopolitano, thanks a lot! Can you also add a fit with the `chebpolN` background in the https://github.com/flarefly/flarefly/blob/main/tests/test_massfitter_binned.py test so that we check that it works?

2022-09-28 12:03 UTC, fgrosa commented on flarefly/fitter.py
> +            elif 'pol' in pdf_name:
move it before the `kde` implementations and add the option `chebpolN` in the docstring

2022-09-28 12:03 UTC, fgrosa commented on flarefly/fitter.py
> +            elif 'pol' in pdf_name:
I would use `chebpol` instead of `pol`, since we might implement other types of polynomial functions in the future

2022-09-28 17:38 UTC, stefanopolitano commented
Hi @fgrosa, I implemented your comments: I am still getting "False" as  result from the `test_massfitter_binned`, but I think it is due to the choice of the parameters of the polynomial function. Anyhow, if you think it is needed, I will investigate a bit more.

2022-09-28 17:49 UTC, fgrosa commented
> Hi @fgrosa, I implemented your comments: I am still getting "False" as result from the `test_massfitter_binned`, but I think it is due to the choice of the parameters of the polynomial function. Anyhow, if you think it is needed, I will investigate a bit more.

The initialisation of the parameters is not the problem, the problem is that you have to loop over the elements of the lists you defined in the `assert` methods in lines 43, 50, 56 since as of now you are passing lists, hence it fails because it is not the expected type

2022-09-30 15:57 UTC, fgrosa commented
@stefanopolitano before we merge, can you please rebase on `origin dev`? Thanks!

2022-09-30 16:13 UTC, stefanopolitano commented on tests/test_massfitter_binned.py
> +        print("WARNING: Chebyshev polynomials require intial parameters to be set.")
I added this print because I set the params. for the pol1 case, if we test a higher polynomial the fit will fail

2022-10-01 15:40 UTC, merged